/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import controle.quiz;

/**
 *
 * @author gabriel.snovaes
 */
public class exercicios extends javax.swing.JFrame {
    
    quiz q = new quiz();

    /**
     * Creates new form exercicios
     */
    public exercicios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG1 = new javax.swing.ButtonGroup();
        BG2 = new javax.swing.ButtonGroup();
        BG3 = new javax.swing.ButtonGroup();
        BG4 = new javax.swing.ButtonGroup();
        BG5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jR10 = new javax.swing.JRadioButton();
        jRcerta1 = new javax.swing.JRadioButton();
        jR11 = new javax.swing.JRadioButton();
        jR12 = new javax.swing.JRadioButton();
        jR13 = new javax.swing.JRadioButton();
        jBq1 = new javax.swing.JButton();
        jL1result = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jRcerto2 = new javax.swing.JRadioButton();
        jR22 = new javax.swing.JRadioButton();
        jR23 = new javax.swing.JRadioButton();
        jR21 = new javax.swing.JRadioButton();
        jR20 = new javax.swing.JRadioButton();
        jBq2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jL2result = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jRcerto3 = new javax.swing.JRadioButton();
        jR30 = new javax.swing.JRadioButton();
        jR31 = new javax.swing.JRadioButton();
        jR32 = new javax.swing.JRadioButton();
        jR33 = new javax.swing.JRadioButton();
        jBq3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jL3result = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jR43 = new javax.swing.JRadioButton();
        jBq4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jL4result = new javax.swing.JLabel();
        jRcerto4 = new javax.swing.JRadioButton();
        jR40 = new javax.swing.JRadioButton();
        jR41 = new javax.swing.JRadioButton();
        jR42 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jR53 = new javax.swing.JRadioButton();
        jBq5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jL5result = new javax.swing.JLabel();
        jRcerto5 = new javax.swing.JRadioButton();
        jR50 = new javax.swing.JRadioButton();
        jR51 = new javax.swing.JRadioButton();
        jR52 = new javax.swing.JRadioButton();
        jLcertos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("Quem foi conhecido por cair por chegar perto do ceu?");

        BG1.add(jR10);
        jR10.setText("Dedalo");

        BG1.add(jRcerta1);
        jRcerta1.setText("Icaro");

        BG1.add(jR11);
        jR11.setText("Lucifer");

        BG1.add(jR12);
        jR12.setText("Hermes");

        BG1.add(jR13);
        jR13.setText("Morpheu");

        jBq1.setText("Escolha");
        jBq1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBq1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jL1result, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jR10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRcerta1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBq1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jR11)
                                        .addGap(18, 18, 18)
                                        .addComponent(jR12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jR13)))))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jR10)
                    .addComponent(jRcerta1)
                    .addComponent(jR11)
                    .addComponent(jR12)
                    .addComponent(jR13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBq1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL1result, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        BG2.add(jRcerto2);
        jRcerto2.setText("Osiris");

        BG2.add(jR22);
        jR22.setText("Zeus");

        BG2.add(jR23);
        jR23.setText("Seth");

        BG2.add(jR21);
        jR21.setText("Xangô");

        BG2.add(jR20);
        jR20.setText("Thor");
        jR20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR20ActionPerformed(evt);
            }
        });

        jBq2.setText("Escolha");
        jBq2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBq2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Qual desses nao tem relação com raio?");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jL2result, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jR20)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBq2)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jR21)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRcerto2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jR22)))
                        .addGap(18, 18, 18)
                        .addComponent(jR23)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jR23)
                    .addComponent(jR22)
                    .addComponent(jRcerto2)
                    .addComponent(jR21)
                    .addComponent(jR20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBq2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL2result, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        BG3.add(jRcerto3);
        jRcerto3.setText("Dêdalo");

        BG3.add(jR30);
        jR30.setText("Dionisio");

        BG3.add(jR31);
        jR31.setText("Hefesto");

        BG3.add(jR32);
        jR32.setText("Platão");

        BG3.add(jR33);
        jR33.setText("Horus");

        jBq3.setText("Escolha");
        jBq3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBq3ActionPerformed(evt);
            }
        });

        jLabel3.setText("Labirinto famoso onde se encontra o Minotauro:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jL3result))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jR30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jR31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBq3)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jR32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRcerto3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jR33)))))
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(110, 110, 110))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRcerto3)
                    .addComponent(jR30)
                    .addComponent(jR31)
                    .addComponent(jR32)
                    .addComponent(jR33))
                .addGap(19, 19, 19)
                .addComponent(jBq3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL3result)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 255));

        BG4.add(jR43);
        jR43.setText("Artemis");

        jBq4.setText("Escolha");
        jBq4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBq4ActionPerformed(evt);
            }
        });

        jLabel5.setText("Personagem conhecido for sofrer um castigo eterno por enganar os deuses");

        BG4.add(jRcerto4);
        jRcerto4.setText("Sísifo");

        BG4.add(jR40);
        jR40.setText("Medusa");

        BG4.add(jR41);
        jR41.setText("Pandora");

        BG4.add(jR42);
        jR42.setText("Aquiles");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jL4result))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jBq4)
                                        .addGap(134, 134, 134))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jRcerto4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jR40)
                                        .addGap(18, 18, 18)
                                        .addComponent(jR41)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jR42)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jR43)))))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRcerto4)
                    .addComponent(jR40)
                    .addComponent(jR41)
                    .addComponent(jR42)
                    .addComponent(jR43))
                .addGap(25, 25, 25)
                .addComponent(jBq4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL4result)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));

        BG5.add(jR53);
        jR53.setText("Euclides");

        jBq5.setText("Escolha");
        jBq5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBq5ActionPerformed(evt);
            }
        });

        jLabel7.setText("Quem é conhecido por ganhar uma luta sem levantar espada");

        BG5.add(jRcerto5);
        jRcerto5.setText("Oxum");
        jRcerto5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRcerto5ActionPerformed(evt);
            }
        });

        BG5.add(jR50);
        jR50.setText("Afrodite");

        BG5.add(jR51);
        jR51.setText("Artemis");

        BG5.add(jR52);
        jR52.setText("Buda");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jL5result))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jRcerto5)
                                    .addGap(18, 18, 18)
                                    .addComponent(jR50)
                                    .addGap(18, 18, 18)
                                    .addComponent(jR51)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jR52)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jR53))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(151, 151, 151)
                                    .addComponent(jBq5))))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRcerto5)
                    .addComponent(jR50)
                    .addComponent(jR51)
                    .addComponent(jR52)
                    .addComponent(jR53))
                .addGap(25, 25, 25)
                .addComponent(jBq5)
                .addGap(18, 18, 18)
                .addComponent(jL5result)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLcertos)
                        .addGap(226, 226, 226)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLcertos)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBq2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBq2ActionPerformed
        // TODO add your handling code here:
        if(jRcerto2.isSelected()){
            q.setopcao(1);
            jL2result.setText("Resposta certa"+q.somar());
        }else if(jR20.isSelected()){
            jL2result.setText("Resposta errada");
        }else if(jR21.isSelected()){
            jL2result.setText("Resposta errada");
        }else if(jR22.isSelected()){
            jL2result.setText("Resposta errada");
        }else if(jR23.isSelected()){
            jL2result.setText("Resposta errada");
        }else{
            jL2result.setText("Opção invalida");
        }
        jLcertos.setText("Certos :"+q.somar());
        jBq2.setEnabled(false);
    }//GEN-LAST:event_jBq2ActionPerformed

    private void jR20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jR20ActionPerformed

    private void jBq1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBq1ActionPerformed
        // TODO add your handling code here:
        if(jRcerta1.isSelected()){
            q.setopcao(1);
            jL1result.setText("Resposta certa"+q.somar());
        }else if(jR10.isSelected()){
            jL1result.setText("Resposta errada");
        }else if(jR11.isSelected()){
            jL1result.setText("Resposta errada");
        }else if(jR12.isSelected()){
            jL1result.setText("Resposta errada");
        }else if(jR13.isSelected()){
            jL1result.setText("Resposta errada");
        }else{
            jL1result.setText("Opção invalida");
        }
        jLcertos.setText("Certos :"+q.somar());
        jBq1.setEnabled(false);
    }//GEN-LAST:event_jBq1ActionPerformed

    private void jBq3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBq3ActionPerformed
        // TODO add your handling code here:
        if(jRcerto3.isSelected()){
            q.setopcao(1);
            jL3result.setText("Resposta certa"+q.somar());
        }else if(jR30.isSelected()){
            jL3result.setText("Resposta errada");
        }else if(jR31.isSelected()){
            jL3result.setText("Resposta errada");
        }else if(jR32.isSelected()){
            jL3result.setText("Resposta errada");
        }else if(jR33.isSelected()){
            jL3result.setText("Resposta errada");
        }else{
            jL3result.setText("Opção invalida");
        }
        jLcertos.setText("Certos :"+q.somar());
        jBq3.setEnabled(false);
    }//GEN-LAST:event_jBq3ActionPerformed

    private void jRcerto5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRcerto5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRcerto5ActionPerformed

    private void jBq4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBq4ActionPerformed
        // TODO add your handling code here:
        if(jRcerto4.isSelected()){
            q.setopcao(1);
            jL4result.setText("Resposta certa"+q.somar());
        }else if(jR40.isSelected()){
            jL4result.setText("Resposta errada");
        }else if(jR41.isSelected()){
            jL4result.setText("Resposta errada");
        }else if(jR42.isSelected()){
            jL4result.setText("Resposta errada");
        }else if(jR43.isSelected()){
            jL4result.setText("Resposta errada");
        }else{
            jL4result.setText("Opção invalida");
        }
        jLcertos.setText("Certos :"+q.somar());
        jBq4.setEnabled(false);
    }//GEN-LAST:event_jBq4ActionPerformed

    private void jBq5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBq5ActionPerformed
        // TODO add your handling code here:
        if(jRcerto5.isSelected()){
            q.setopcao(1);
            jL5result.setText("Resposta certa"+q.somar());
        }else if(jR50.isSelected()){
            jL5result.setText("Resposta errada");
        }else if(jR51.isSelected()){
            jL5result.setText("Resposta errada");
        }else if(jR52.isSelected()){
            jL5result.setText("Resposta errada");
        }else if(jR53.isSelected()){
            jL5result.setText("Resposta errada");
        }else{
            jL5result.setText("Opção invalida");
        }
        jLcertos.setText("Certos :"+q.somar());
        jBq5.setEnabled(false);
    }//GEN-LAST:event_jBq5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(exercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(exercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(exercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(exercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new exercicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BG1;
    private javax.swing.ButtonGroup BG2;
    private javax.swing.ButtonGroup BG3;
    private javax.swing.ButtonGroup BG4;
    private javax.swing.ButtonGroup BG5;
    private javax.swing.JButton jBq1;
    private javax.swing.JButton jBq2;
    private javax.swing.JButton jBq3;
    private javax.swing.JButton jBq4;
    private javax.swing.JButton jBq5;
    private javax.swing.JLabel jL1result;
    private javax.swing.JLabel jL2result;
    private javax.swing.JLabel jL3result;
    private javax.swing.JLabel jL4result;
    private javax.swing.JLabel jL5result;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLcertos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jR10;
    private javax.swing.JRadioButton jR11;
    private javax.swing.JRadioButton jR12;
    private javax.swing.JRadioButton jR13;
    private javax.swing.JRadioButton jR20;
    private javax.swing.JRadioButton jR21;
    private javax.swing.JRadioButton jR22;
    private javax.swing.JRadioButton jR23;
    private javax.swing.JRadioButton jR30;
    private javax.swing.JRadioButton jR31;
    private javax.swing.JRadioButton jR32;
    private javax.swing.JRadioButton jR33;
    private javax.swing.JRadioButton jR40;
    private javax.swing.JRadioButton jR41;
    private javax.swing.JRadioButton jR42;
    private javax.swing.JRadioButton jR43;
    private javax.swing.JRadioButton jR50;
    private javax.swing.JRadioButton jR51;
    private javax.swing.JRadioButton jR52;
    private javax.swing.JRadioButton jR53;
    private javax.swing.JRadioButton jRcerta1;
    private javax.swing.JRadioButton jRcerto2;
    private javax.swing.JRadioButton jRcerto3;
    private javax.swing.JRadioButton jRcerto4;
    private javax.swing.JRadioButton jRcerto5;
    // End of variables declaration//GEN-END:variables
}
