/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.visao;

import br.com.controle.calculo;
import javax.swing.JOptionPane;

/**
 *
 * @author gabriel.snovaes
 */
public class calculadora extends javax.swing.JFrame {
    calculo c = new calculo();
    /**
     * Creates new form calculadora
     */
    public calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLvalor1 = new javax.swing.JLabel();
        jLvalor2 = new javax.swing.JLabel();
        jSomar = new javax.swing.JButton();
        jSubtrair = new javax.swing.JButton();
        jMultiplicar = new javax.swing.JButton();
        jDivisao = new javax.swing.JButton();
        jLresultado = new javax.swing.JLabel();
        jTvalor1 = new javax.swing.JTextField();
        jTvalor2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLvalor1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLvalor1.setText("Valor 1:");

        jLvalor2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLvalor2.setText("Valor 2:");

        jSomar.setBackground(new java.awt.Color(153, 153, 255));
        jSomar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jSomar.setForeground(new java.awt.Color(255, 255, 255));
        jSomar.setText("+");
        jSomar.setToolTipText("");
        jSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSomarActionPerformed(evt);
            }
        });

        jSubtrair.setBackground(new java.awt.Color(153, 153, 255));
        jSubtrair.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jSubtrair.setForeground(new java.awt.Color(255, 255, 255));
        jSubtrair.setText("-");
        jSubtrair.setToolTipText("");
        jSubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubtrairActionPerformed(evt);
            }
        });

        jMultiplicar.setBackground(new java.awt.Color(153, 153, 255));
        jMultiplicar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMultiplicar.setForeground(new java.awt.Color(255, 255, 255));
        jMultiplicar.setText("*");
        jMultiplicar.setToolTipText("");
        jMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMultiplicarActionPerformed(evt);
            }
        });

        jDivisao.setBackground(new java.awt.Color(153, 153, 255));
        jDivisao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jDivisao.setForeground(new java.awt.Color(255, 255, 255));
        jDivisao.setText("/");
        jDivisao.setToolTipText("");
        jDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDivisaoActionPerformed(evt);
            }
        });

        jLresultado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLresultado.setForeground(new java.awt.Color(51, 51, 255));
        jLresultado.setText("0.00");
        jLresultado.setAlignmentX(2.0F);
        jLresultado.setAlignmentY(2.0F);
        jLresultado.setPreferredSize(new java.awt.Dimension(30, 30));

        jTvalor1.setColumns(4);
        jTvalor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTvalor1ActionPerformed(evt);
            }
        });

        jTvalor2.setColumns(4);
        jTvalor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTvalor2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLvalor1)
                            .addComponent(jLvalor2))
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTvalor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTvalor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jSomar)
                                .addGap(12, 12, 12)
                                .addComponent(jSubtrair)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jMultiplicar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDivisao)
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLvalor1)
                    .addComponent(jTvalor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLvalor2)
                    .addComponent(jTvalor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSomar)
                    .addComponent(jSubtrair)
                    .addComponent(jMultiplicar)
                    .addComponent(jDivisao))
                .addGap(30, 30, 30)
                .addComponent(jLresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jLresultado.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTvalor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTvalor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTvalor2ActionPerformed

    private void jSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSomarActionPerformed
        if(jTvalor1.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Campo Obrigatório");
            jTvalor1.requestFocus();
        }else if(jTvalor2.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Campo Obrigatório");
            jTvalor2.requestFocus();
        }
        else{
             try{
                c.setN1(Double.valueOf( jTvalor1.getText()));
                c.setN2(Double.valueOf( jTvalor2.getText()));
                jLresultado.setText(""+c.somar());
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Apenas Numeros");
                    jTvalor1.requestFocus();
            }
        }
    }//GEN-LAST:event_jSomarActionPerformed

    private void jSubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubtrairActionPerformed
        // TODO add your handling code here:
        if(jTvalor1.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Campo Obrigatório");
            jTvalor1.requestFocus();
        }else if(jTvalor2.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Campo Obrigatório");
            jTvalor2.requestFocus();    
        }else{
            try{
                c.setN1(Double.valueOf( jTvalor1.getText()));
                c.setN2(Double.valueOf( jTvalor2.getText()));
                jLresultado.setText(""+c.subtrair());
            } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Apenas Numeros");
                    jTvalor1.requestFocus();
            }
        }
    }//GEN-LAST:event_jSubtrairActionPerformed

    private void jTvalor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTvalor1ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jTvalor1ActionPerformed

    private void jMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMultiplicarActionPerformed
        if(jTvalor1.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Campo Obrigatório");
            jTvalor1.requestFocus();
            
        }else if(jTvalor2.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Campo Obrigatório");
            jTvalor2.requestFocus();
            
        }else{
            try {
            c.setN1(Double.valueOf( jTvalor1.getText()));
            c.setN2(Double.valueOf( jTvalor2.getText()));
            jLresultado.setText(""+c.multiplicar());
            
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Apenas Numeros");
                    jTvalor1.requestFocus();
            }    
        }
    }//GEN-LAST:event_jMultiplicarActionPerformed

    private void jDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDivisaoActionPerformed
        // TODO add your handling code here:
        if(jTvalor1.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Campo Obrigatório");
            jTvalor1.requestFocus();
        }else if(jTvalor2.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Campo Obrigatório");
            jTvalor2.requestFocus();
        }else{
            try{
                c.setN1(Double.valueOf( jTvalor1.getText()));
                c.setN2(Double.valueOf( jTvalor2.getText()));
                jLresultado.setText(""+c.dividir());
                } catch (NumberFormatException e) {
                            JOptionPane.showMessageDialog(null, "Apenas Numeros");
                            jTvalor1.requestFocus();
                }
        }
    }//GEN-LAST:event_jDivisaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jDivisao;
    private javax.swing.JLabel jLresultado;
    private javax.swing.JLabel jLvalor1;
    private javax.swing.JLabel jLvalor2;
    private javax.swing.JButton jMultiplicar;
    private javax.swing.JButton jSomar;
    private javax.swing.JButton jSubtrair;
    private javax.swing.JTextField jTvalor1;
    private javax.swing.JTextField jTvalor2;
    // End of variables declaration//GEN-END:variables
}
